### ISSUE TITLE
Add Inbuilt hash text (md5) on mirror/leech result 

### ISSUE THREAD

**Issue by sonhak-18** [weebzone/WZML-X#124]
<img width="327" alt="W10" src="https://user-images.githubusercontent.com/100685253/214539372-b53dd2a2-1a7b-4820-9e6d-351f867340fb.png">

Is it possible to add the hash result (md5 Checksum) to the mirror or leech result as shown in the example? Considering that I think the hash command will run slowly because it has to download the file first on telegram, and I think it would be more efficient to add it directly to the mirror result.

**Comment by weebzone** [comment]
@sonhak-18 okk

**Comment by SilentDemonSD** [comment]
Added in Leeched File caption as {md5_hash}
