### ISSUE TITLE
Request to add categories while uploading to Gdrive folders 

### ISSUE THREAD

**Issue by Rupash2005** [weebzone/WZML-X#187]
Request you to add this [Categories ](https://github.com/junedkh/jmdkh-mltb#multi-category-ids) feature to upload to gdrive in different pre define folders

**Comment by SilentDemonSD** [comment]
> Request you to add this [Categories ](https://github.com/junedkh/jmdkh-mltb#multi-category-ids) feature to upload to gdrive in different pre define folders

It is now Added ! ENJOY
