### ISSUE TITLE
More than one file leech

### ISSUE THREAD

**Issue by thomassch8861** [weebzone/WZML-X#204]
I am leeching 81 files using /l1 -i 81 command. So each time bot ask to upload which dump channel I created. Add an argument or option to upload all the files to all the leech channels after selecting upload to all button without asking one by one.

**Comment by weebzone** [comment]
Already present 
18. -c or -category : Gdrive category to Upload, Specific Name (case insensitive)
19. -ud or -dump : Dump category to Upload, Specific Name (case insensitive) or chat_id or chat_username
