### ISSUE TITLE
Bug in DDL gofile after upload no reply are coming from bot

### ISSUE THREAD

**Issue by sourabhbeni** [weebzone/WZML-X#209]
**Describe the bug**
When using mirror with ddl go file process is completed without error but no output link is showing .
**To Reproduce**
1. Video file using /mirror cmd .
2. Before/after/while Upload ..
3. Logs checked no error showing successfully uploaded
![E6FE8D5B-E602-400D-A86D-B83332A7E188](https://github.com/weebzone/WZML-X/assets/46120445/cdca0175-44d5-4446-bef8-0830fbc8f21c)
![F9EC1B22-90B4-453D-A907-336393844DDC](https://github.com/weebzone/WZML-X/assets/46120445/d5c5cb88-6905-4e87-b694-17eb024e0893)

**Comment by SilentDemonSD** [comment]
I

> **Describe the bug** When using mirror with ddl go file process is completed without error but no output link is showing . **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Video file using /mirror cmd .
> 2. Before/after/while Upload ..
> 3. Logs checked no error showing successfully uploaded
>    ![E6FE8D5B-E602-400D-A86D-B83332A7E188](https://user-images.githubusercontent.com/46120445/258500932-cdca0175-44d5-4446-bef8-0830fbc8f21c.png)
>    ![F9EC1B22-90B4-453D-A907-336393844DDC](https://user-images.githubusercontent.com/46120445/258500950-d5c5cb88-6905-4e87-b694-17eb024e0893.png)

It is Fixed ! Let us know if any issue still persists
