### ISSUE TITLE
ytdl is failed 403 http error

### ISSUE THREAD

**Issue by Mohanish7777777** [weebzone/WZML-X#214]
Download Stopped!
┠ Task for: @user
┃
┠ Due To: ERROR:  [download] Got error: HTTP Error 403: Forbidden
┠ Mode:  #GDrive | #ytdlp
┖ Elapsed: 40s

**Comment by SilentDemonSD** [comment]
Update to Lastest yt-dlp, it will be Fixed, Use -opt quality for --list-formats Issue
