### ISSUE TITLE
Add shortened links to /list cmd's searched links

### ISSUE THREAD

**Issue by theseeker99** [weebzone/WZML-X#95]
Hey, can you please add shortened links to /list cmd's searched links. bcuz user bypass shortened mirror links using this cmd
![Desktop Screenshot 2022 12 30 - 00 24 50 63](https://user-images.githubusercontent.com/110098713/209996737-f1d6ddf9-2b8a-44d2-a41f-64699e7208b5.png)

**Comment by Rupash2005** [comment]
is this still not fixed i needed /list cmd with shortened links

**Comment by Rupash2005** [comment]
Bro is this has been fixed ?

**Comment by theseeker99** [comment]
> Bro is this has been fixed ?

Yes. It's fixed

**Comment by Rupash2005** [comment]
Bro still not fixed after updating and redeploying , Still showing direct download link instead of shortened mirror links using this /list cmd

Pls  help
